### ISSUE TITLE
rt.repo points towards red hat internal RPM repo

### ISSUE THREAD

**Issue by novacain1** [redhat-nfvpe/container-perf-tools#1]
https://github.com/redhat-nfvpe/container-perf-tools/blob/master/rt.repo is pointing towards an internal URL inside of Red Hat.  This would preclude this from working externally I would think.

**Comment by jianzzha** [comment]
this is fixed by: 
https://github.com/redhat-nfvpe/container-perf-tools/commit/181e97c9ce02cc082570984a5bf3cb1a79eeafa4
